server:
    port: 8080

mysql:
    host: localhost
    port: 3307
    username: app_cam
    password: secret
    database: hanet-camera-db
    maxIdleConns: 10
    maxOpenConns: 100
    maxConnLifetime: 3600

logger:
    log_level: debug
    file_log_name: ./storages/logs/dev.001.log
    max_size: 500
    max_backups: 3
    max_age: 28
    compress: true