server:
    port: 8080

mysql:
    host: localhost
    port: 3307
    username: app_cam
    password: secret
    database: hanet-camera-db
    maxIdleConns: 10
    maxOpenConns: 100
    maxConnLifetime: 3600