server:
    port: 8080

databases:
    -   user: admin
        password: admin
        host: localhost
        dbname: shop-dev

    -   user: admin
        password: admin
        host: localhost
        dbname: shop-dev

security:
    secret